// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.security.account.domain;

import java.util.List;
import java.util.Random;
import org.springframework.security.account.domain.Account;
import org.springframework.stereotype.Component;

privileged aspect AccountDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AccountDataOnDemand: @Component;
    
    private Random AccountDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Account> AccountDataOnDemand.data;
    
    public Account AccountDataOnDemand.getNewTransientAccount(int index) {
        org.springframework.security.account.domain.Account obj = new org.springframework.security.account.domain.Account();
        java.lang.String username = "username_" + index;
        if (username.length() > 64) {
            username  = username.substring(0, 64);
        }
        obj.setUsername(username);
        java.lang.String email = "email_" + index;
        if (email.length() > 64) {
            email  = email.substring(0, 64);
        }
        obj.setEmail(email);
        java.lang.String firstName = "firstName_" + index;
        if (firstName.length() > 25) {
            firstName  = firstName.substring(0, 25);
        }
        obj.setFirstName(firstName);
        java.lang.String lastName = "lastName_" + index;
        if (lastName.length() > 25) {
            lastName  = lastName.substring(0, 25);
        }
        obj.setLastName(lastName);
        return obj;
    }
    
    public Account AccountDataOnDemand.getSpecificAccount(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Account obj = data.get(index);
        return Account.findAccount(obj.getId());
    }
    
    public Account AccountDataOnDemand.getRandomAccount() {
        init();
        Account obj = data.get(rnd.nextInt(data.size()));
        return Account.findAccount(obj.getId());
    }
    
    public boolean AccountDataOnDemand.modifyAccount(Account obj) {
        return false;
    }
    
    public void AccountDataOnDemand.init() {
        data = org.springframework.security.account.domain.Account.findAccountEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Account' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.springframework.security.account.domain.Account>();
        for (int i = 0; i < 10; i++) {
            org.springframework.security.account.domain.Account obj = getNewTransientAccount(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
